- name: copy folder template
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"/"{{item.name}}"
    url: http://44.201.85.251:8080
    user: admin
    password: admin123

