- name: Create a jenkins job 
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{ item }}"
    url: http://172.31.94.184:8080
    user: admin
    password: admin123

    loop:
      - frontend
      - catalogue
      - cart

