- name: Create a jenkins folder-{{item}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://44.201.85.251:8080
    user: admin
    password: admin123
  loop:
    - ci-pipeline

- name: create jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - { name: "frontend", dir: "ci-pipeline" }

     

