- name: Create a jenkins folder-"{{item.dir}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://44.201.85.251:8080
    user: admin
    token: 113535f946a58b0bc6a6ed8fed0cf136db
  loop:
    - ci-pipeline

- name: create jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - { name: "frontend", dir: "ci-pipeline" }

     

