- name: copy job.xml template
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: Create a jenkins job-"{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://44.201.85.251:8080
    user: admin
    password: admin123
