- name: copy template
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/"{{item}}".xml
  loop:
    - job
    - folder

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/"{{item}}".xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://44.201.85.251:8080
    user: admin
    password: "{{jenkins_pass}}"
  loop:
    - job
    - folder

