- name: copy template
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://44.201.85.251:8080
    user: admin
    password: "{{jenkins_pass}}"

