- name: copy job.xml template
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}.xml

- name: Create a jenkins job-"{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://44.201.85.251:8080
    user: admin
    token: 113535f946a58b0bc6a6ed8fed0cf136db

